# This file was moved from /cloud_build/cloudbuild.arc-dev.ci.yaml because the Google Cloud Build GitHub App only supports a single config file at the root of the project.
# It should be identical to /cloud_build/cloudbuild.arc-dev.yaml, except for these header comments and the version specified in the 'gcloud app deploy' command.
# See https://cloud.google.com/cloud-build/docs/run-builds-with-github-checks and https://issuetracker.google.com/issues/113814820 for more information.

steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

# TODO: Resolve issue with Cloud Build after updating tests
#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-arc-dev'
  - 'API_URL=https://api.dev.alight.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=false'
  - 'TOP_KEYWORDS_ENABLED=true'
  - 'TOP_KEYWORDS_API_URL=https://kujakuja.co/kujakuja/alight/keywords/v1'
  - 'DATA_STUDIO_GRAPH_URL='
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'
  - 'TOP_KEYWORDS_LOGIN_USERNAME'
  - 'TOP_KEYWORDS_LOGIN_PASSWORD'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--no-promote', '--version=cloud-build-ci', '--project=kujakuja-arc-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcTLhIatdLMO5FG+QB3zuIKrV/oCVP7YVFpGK8fsfs0YSUAD8O7eKEq+/0zUMnIH6ZLekdVs+dvNuz96hb/opcndG0NSGeFDNApF0wq2RULFBst/BHxumpkzKOQtKf56UkY98cRMPgXtLOxUZmZ19/wMl
      TOP_KEYWORDS_LOGIN_USERNAME: CiQAnpDxcRFMxfZ+7Y3Cu6xbBdG7yogLpWKPNvPvBPUzHU1hrGISMQD8O7eKRYS4MbkN1lCMzI5+mxi86+xnyyuxqpQmMaInlUJBKas3djye6glfajqCiKQ=
      TOP_KEYWORDS_LOGIN_PASSWORD: CiQAnpDxcR2cuRhBPB8/OfO4pFtooPqyaC9q9aPEmWtMFdbIi64SOQD8O7eKmfzAmu+KhOxfj555jAGvYCERKlE2BucMRnCbNXBytYaSKbS2IAXDXFsnC9gxrKEooPPUNw==

timeout: '1800s'
