steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-imc-dev'
  - 'API_URL=https://api.dev.imc.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=true'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL='
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-imc-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcWThIj3dBMiJ54hnmLorHxo5/4cPm/+WfbbAlO2Wn0USUAD8O7eKilUGD0wqH3aV4PrRl3YA2yOWfCdvgVYzl+BoBUZLWHV8qr2ONVPHJh/XSUlY1TyndJgmksK7WHw9Ro64Lagcvy4lXlD5kB6jmf5X

timeout: '1800s'
