steps:

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-u4u-dev'
  - 'API_URL=https://api.dev.u4u.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=true'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL='
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-u4u-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxca2/4nOckHDwk5xUN3jdWsq4qDSgGvjV/F0U1xOVBBASUAD8O7eKaYro8NF09CvxN99y7IuiqEYTarSrJ6YJgAG3mcdZ+lOQDQOEUD8404tfgZXaBxBbbwQDKoj5xfcvjJQFaF+hzLa8ewqEEn3m6Y1o

timeout: '1800s'
