steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-arc-live'
  - 'API_URL=https://api.alight.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=false'
  - 'TOP_KEYWORDS_ENABLED=true'
  - 'TOP_KEYWORDS_API_URL=https://kujakuja.co/kujakuja/alight/keywords/v1'
  - 'DATA_STUDIO_GRAPH_URL=https://datastudio.google.com/embed/reporting/a32d4a8e-c874-4345-bf9c-487e655f4089/page/6kLq'
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'
  - 'TOP_KEYWORDS_LOGIN_USERNAME'
  - 'TOP_KEYWORDS_LOGIN_PASSWORD'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-arc-live']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcaiBl3wXj7kZGMK8/bFYhfQD8DHjVWiPFGc5PCm6zqsSUAD8O7eKN0Z+NsWdPnrUInQwkQQMDLdB1M3S/Z16e5yy8TzXC+WLj+zD4vlffUIbdDVOkIspTtFs9AeuigJ2T2OGQHKsjl62K/jEnHNPJA4L
      TOP_KEYWORDS_LOGIN_USERNAME: CiQAnpDxcRFMxfZ+7Y3Cu6xbBdG7yogLpWKPNvPvBPUzHU1hrGISMQD8O7eKRYS4MbkN1lCMzI5+mxi86+xnyyuxqpQmMaInlUJBKas3djye6glfajqCiKQ=
      TOP_KEYWORDS_LOGIN_PASSWORD: CiQAnpDxcR2cuRhBPB8/OfO4pFtooPqyaC9q9aPEmWtMFdbIi64SOQD8O7eKmfzAmu+KhOxfj555jAGvYCERKlE2BucMRnCbNXBytYaSKbS2IAXDXFsnC9gxrKEooPPUNw==

timeout: '1800s'
