steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-datos-dev'
  - 'API_URL=https://api.dev.datos.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=false'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL='
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-datos-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcbs5zi7JFdhNwA/DK4ase7w7I6XQnkKYLMqQ+DX3e8kSTwD8O7eK5xb6p08M5WalfIc+8EmlyTs9p3vsW/DMOhEi9FMBTn1u/7wg9TNBwGLWqrDvrb5BfPmXwHaZc1ak+ozIKZNhT2LhXbrI95pMMtM=

timeout: '1800s'
