steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-aah-live'
  - 'API_URL=https://api.aah.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=true'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL=https://datastudio.google.com/embed/reporting/8eda591f-01d0-4045-b0fd-13cb4a78e1f5/page/yipdB'
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-aah-live']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcQwnddjPOH2N2ONlZCxEoQxCwP9Jnk5b9aXN1kHS+kkSUAD8O7eKIlMG9sAPtapQuZ3Z1gK7UWgbUnwkt59dYRB7cAcw4ECf6SDEvSh0sXsCfk5EZDhvNQLxgXOQZLEqLTkCbFm6JatLTwwxhkqZ4zpc

timeout: '1800s'
