steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-oram-dev'
  - 'API_URL=https://api.dev.oram.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=true'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL=https://lookerstudio.google.com/embed/reporting/7362e2f5-a804-4e38-b5d4-0b1b8ee0c286/page/r5w5C'
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-oram-dev']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcaaOH+BuFipqSv9rNP4SMFCZSLZQTVSVTW47CXRnI4MSUAD8O7eKGvgrl3FuCP6FOMDlJTS2gg8ck+ih+wxkT84vIJMiCvpDvvsinO5ryBjuf5F8zbfgu/o6pgexaj5MDAEHjPKyGqW7J6IBW9IXCZzi

timeout: '1800s'
