steps:

# we're using Node.js v12 because Object.fromEntries (used in /src/helpers.js) is not supported in earlier versions
- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['install']

#- name: 'node:16.14.2'
#  entrypoint: 'npm'
#  args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'GCP_PROJECT_ID=kujakuja-crc-live'
  - 'API_URL=https://api.crc.kujakuja.com/api/v3/'
  - 'LOGIN_REQUIRED=true'
  - 'TOP_KEYWORDS_ENABLED=false'
  - 'DATA_STUDIO_GRAPH_URL=https://datastudio.google.com/embed/reporting/170fd186-53f2-4634-ad1b-198b2508a1ee/page/yipdB'
  secretEnv:
  - 'GOOGLE_TRANSLATE_API_KEY'

- name: 'node:16.14.2'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--promote', '--version=$TAG_NAME', '--project=kujakuja-crc-live']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      GOOGLE_TRANSLATE_API_KEY: CiQAnpDxcUtU93f7iOqSsE7FR3l3XSBnHm/uAaMVoP1VjIAIFvwSUAD8O7eKksANAV9YhIQCsM0fqI1KRUD0XghmZ1ryZyCAiEhr9VAsML3ZauzhqGPMq1u79RqIvG1ZZQb03rvldsCSGgQK/Xtrz4nUIF+eXBxe

timeout: '1800s'
